version: "3.9"

services:
  misp-pipeline:
    build: .
    container_name: misp-pipeline

    env_file:
      - .env
    volumes:
      - ./Assets:/app/Assets
      - ./reports:/app/reports
    working_dir: /app
    command: python main.py
    restart: unless-stopped


