"""Stage 3 — BERTopic topic modelling over event text."""

import json
import logging
import pathlib
from typing import Any
from pipeline.base import Stage
from pipeline.event import CurationEvent

logger = logging.getLogger(__name__)

# Relevance map is auto-generated by train_topics.py on every retrain.
# Edit models/topic_relevance_map.json to manually tune scores between retrains.
_MAP_PATH = pathlib.Path(__file__).parent.parent / "models" / "topic_relevance_map.json"


def _load_relevance_map() -> dict[str, float]:
    if _MAP_PATH.exists():
        try:
            return json.loads(_MAP_PATH.read_text(encoding="utf-8"))
        except Exception as exc:
            logger.warning("Failed to load topic_relevance_map.json: %s", exc)
    logger.warning(
        "topic_relevance_map.json not found — topic scores will be 0.0. "
        "Run train_topics.py to generate it."
    )
    return {}


TOPIC_RELEVANCE_MAP: dict[str, float] = _load_relevance_map()


def _resolve_relevance(topic_label: str) -> float:
    """Look up a topic label in the relevance map; return 0.0 if unmapped."""
    return TOPIC_RELEVANCE_MAP.get(topic_label, 0.0)


def _event_to_text(raw: dict[str, Any]) -> str:
    """Concatenate all useful text fields from a raw MISP event dict."""
    parts = [
        raw.get("info", ""),
        raw.get("description", ""),
        " ".join(t.get("name", "") for t in raw.get("Tag", [])),
        " ".join(
            f"{gc.get('value', '')} {gc.get('description', '')}"
            for g in raw.get("Galaxy", [])
            for gc in g.get("GalaxyCluster", [])
        ),
        " ".join(
            a.get("value", "") for a in raw.get("Attribute", [])
            if a.get("type") in {"text", "comment", "vulnerability"}
        ),
    ]
    return " ".join(filter(None, parts))


def _apply_topic(event: CurationEvent, topic_id: int, model: Any) -> None:
    """Populate event.topics, event.topic_label, and event.topic_relevance_score."""
    if topic_id == -1:
        event.topics = [("outlier", 0.0)]
        event.topic_label = "outlier"
        event.topic_relevance_score = 0.1  # neutral floor — not confirmed relevant but not penalised
        return

    words = model.get_topic(topic_id) or []
    event.topics = [(w, round(score, 4)) for w, score in words[:8]]
    label = "_".join(w for w, _ in words[:3])
    event.topic_label = label
    event.topic_relevance_score = _resolve_relevance(label)
    logger.debug(
        "Event %s → topic_id=%d label=%s relevance=%.2f",
        event.misp_id, topic_id, label, event.topic_relevance_score,
    )


class TopicModelStage(Stage):
    """Assigns a topic to each event and looks up its profile relevance."""

    @property
    def name(self) -> str:
        return "topic_model"

    def __init__(self, model: Any = None) -> None:
        self._model = model

    def process_batch(self, events: list[CurationEvent]) -> list[CurationEvent]:
        if self._model is None:
            for e in events:
                e.topics = []
                e.topic_label = ""
                e.topic_relevance_score = 0.0
            return events

        texts = [_event_to_text(e.raw) for e in events]
        topic_ids, _ = self._model.transform(texts)

        for event, topic_id in zip(events, topic_ids):
            _apply_topic(event, int(topic_id), self._model)

        return events

    def process(self, event: CurationEvent) -> CurationEvent:
        if self._model is None:
            event.topics = []
            event.topic_label = ""
            event.topic_relevance_score = 0.0
            return event

        topic_ids, _ = self._model.transform([_event_to_text(event.raw)])
        _apply_topic(event, int(topic_ids[0]), self._model)
        return event
